name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to directory with main.py and print current directory
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -la
      - name: Create logs directory
        run: mkdir -p logs
      - name: Set permissions for logs directory
        run: chmod -R 777 logs
      - name: Create setup log file
        run: touch logs/setup.log
      - name: Create run log file
        run: touch logs/python-app.log
      - name: Create app log file
        run: touch logs/app.log
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip >> logs/setup.log 2>&1
      - name: Install necessary packages
        run: |
          sudo apt-get update >> logs/setup.log 2>&1
          sudo apt-get upgrade -y >> logs/setup.log 2>&1
          echo "::set-output name=result::$result" >> logs/setup.log 2>&1
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y selenium-server-standalone
          sudo apt-get install -y chromedriver
          sudo apt-get update
          sudo apt-get upgrade -y
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          pwd >> logs/setup.log
          pip install -r requirements.txt >> logs/setup.log 2>&1
      - name: python-main
        run: |
          cd ${{ github.workspace }}
          ls -la >> logs/python-app.log
          python -m pip list >> logs/setup.log 2>&1
      - name: Run main python app
        run: |
          python main.py >> logs/app.log 2>&1
          echo "::set-output name=result::$result" >> logs/app.log 2>&1
      - name: Archive test output as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: logs/python-app.log
