name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to directory with main.py and print current directory
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -la

      - name: Create log file
        run: touch logs/python-app.log

      - name: python-main
        run: |
          cd ${{ github.workspace }}
          python -m venv venv
          source venv/bin/activate
          python -m pip install .
          python -m setup.py install

      - name: Deactivate virtual environment
        run: deactivate

      - name: Archive test output as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: logs/python-app.log
